[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4"
ark-ff = "0.4"
ark-std = "0.4"
sha2 = "0.10"
byteorder = "1.4"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
flate2 = "1.0"

[dev-dependencies]
rand_chacha = "0.3"