[package]
name = "cuda_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
# Expander Compiler Collection for zkCUDA (vendored locally for compatibility)
expander_compiler = { path = "../vendor/expander_compiler" }

# Utilities
anyhow = "1.0"
